In [1]:
from scdesigner.minimal.copula import Copula
from scdesigner.minimal.standard_copula import StandardCopula
import numpy as np
import scanpy as sc
adata = sc.datasets.pbmc3k()[:, :300]

model = StandardCopula()
model.setup_data(adata, {"group": "~ 1"})
model.fit(lambda y, _: np.random.uniform(size=y.shape), top_k=5)

Estimating top-k copula covariance: 100%|██████████| 3/3 [00:00<00:00, 17.42it/s]


In [6]:
import torch
model.pseudo_obs({"group": torch.ones((10, 1))})

array([[0.54956268, 0.29835887, 0.14162614, ..., 0.61093045, 0.45998613,
        0.91564273],
       [0.41600778, 0.37388275, 0.84264573, ..., 0.0375898 , 0.78281628,
        0.59443243],
       [0.29583273, 0.45673984, 0.42394385, ..., 0.41997241, 0.25476446,
        0.94792619],
       ...,
       [0.65155866, 0.85611047, 0.82753773, ..., 0.01209719, 0.32764404,
        0.80745558],
       [0.115253  , 0.45718688, 0.07340301, ..., 0.10722618, 0.72896669,
        0.35781962],
       [0.44913312, 0.022874  , 0.93512333, ..., 0.98765416, 0.34196975,
        0.66853767]], shape=(10, 300))

In [20]:
class DummyCopula(Copula):
    def fit(self):
        pass
    def likelihood(self):
        pass
    def num_params(self):
        return 0
    def pseudo_obs(self, x_dict):
        return np.random.uniform(size=(x_dict["group"].shape[0], self.n_outcomes))

model = DummyCopula({"group": "~ 1"})
model.setup_data(adata, {"group": "~ 1"})
model.fit()
model.pseudo_obs({"group": torch.ones((10, 1))})

array([[0.10284701, 0.41000609, 0.69596772, ..., 0.52144126, 0.25914261,
        0.8470127 ],
       [0.13863507, 0.58952173, 0.41871633, ..., 0.93874473, 0.38100497,
        0.13370794],
       [0.24018158, 0.22609427, 0.37927223, ..., 0.12047578, 0.35004729,
        0.07259962],
       ...,
       [0.78629411, 0.93918412, 0.40680509, ..., 0.49816796, 0.92887604,
        0.52067573],
       [0.07300059, 0.70594734, 0.69085288, ..., 0.56373097, 0.83243652,
        0.74598954],
       [0.25189826, 0.51231951, 0.89125815, ..., 0.73327608, 0.0861878 ,
        0.24943634]], shape=(10, 300))

In [28]:
from scdesigner.minimal.copula import CovarianceStructure
import pandas as pd

sigma = np.random.uniform(size=(5, 5))
modeled_names = ["A", "B", "C", "D", "E"]
pd.DataFrame(sigma, columns=modeled_names, index=modeled_names)


CovarianceStructure(sigma, modeled_names)

A         B         C         D         E
A  0.617885  0.329233  0.636680  0.929366  0.982095
B  0.471134  0.247105  0.605505  0.582059  0.440104
C  0.267105  0.271201  0.987214  0.450775  0.744959
D  0.664606  0.438584  0.922960  0.716155  0.923021
E  0.350068  0.335663  0.553483  0.197812  0.137249

In [25]:
sigma

array([[0.14976851, 0.71129941, 0.14026614, 0.88707355, 0.45163096],
       [0.63830759, 0.22772043, 0.65607865, 0.69900385, 0.50699465],
       [0.7994376 , 0.44921599, 0.28379812, 0.39800531, 0.50783429],
       [0.44839211, 0.30037179, 0.91054747, 0.16783024, 0.73104381],
       [0.76080346, 0.30028137, 0.86764418, 0.00853099, 0.4808472 ]])